### ISSUE TITLE
Requests without SNI fail with: "The server mode SSL must use a certificate with the associated private key."

### ISSUE THREAD

**Issue by ghost** [natemcmaster/LettuceEncrypt#122]
**Describe the bug**
If LettuceEncrypt is loaded but not configured, and the host is configured to use a specific SSL certificate, requests to the server without SNI will fail with the connection being dropped. This makes it difficult to support installations where LettuceEncrypt is not required.

Adding a reference to LettuceEncrypt should not break SSL configuration unless the LettuceEncrypt configuration has been defined.

**To Reproduce**
1. Create a new ASP.Net Core 3.0 API project.
2. Add a reference to LettuceEncrypt 1.0.0.0, but don't add any LettuceEncrypt configuration to `appsettings.json` or changes to `Startup.cs`.
3. Run the project as a self-hosted Kestrel web server on a Windows 10 host.
4. Make an HTTPS request to the server that doesn't include the Server Name Indication extension, or with SNI but for a hostname that the server isn't expecting (eg: "bad.host").
(I've been using [sslscan](https://github.com/rbsec/sslscan) with `--sni-name=bad.host` for this).
5. Request succeeds and the server returns the ASP.Net Development Certificate for localhost.
6. Stop the project.
7. Add a call to `services.AddLettuceEncrypt()` in the ConfigureServices method of `Startup.cs`.
8. Run the project again, and repeat the same HTTPS request from step 4.
9. The HTTPS connection fails as the server doesn't provide a certificate. The following exception is output from the Kestrel library:
```csharp
System.Security.Authentication.AuthenticationException: The server mode SSL must use a certificate with the associated private key.
   at System.Net.Security.SecureChannel.AcquireServerCredentials(Byte[]& thumbPrint, Byte[] clientHello)
   at System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   at System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.ProcessAuthentication(LazyAsyncResult lazyResult, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.BeginAuthenticateAsServer(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken, AsyncCallback asyncCallback, Object asyncState)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsServerAsync>b__69_0(SslServerAuthenticationOptions arg1, CancellationToken arg2, AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2](Func`5 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory.FromAsync[TArg1,TArg2](Func`5 beginMethod, Action`1 endMethod, TArg1 arg1, TArg2 arg2, Object state)
   at System.Net.Security.SslStream.AuthenticateAsServerAsync(SslServerAuthenticationOptions sslServerAuthenticationOptions, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.InnerOnConnectionAsync(ConnectionContext context)
````

**Expected behavior**
Any SSL certificate selection logic in LettuceEncrypt should be bypassed unless LettuceEncrypt has configuration defining the certificates that should be used.

**Additional context**
This seems to have been introduced since McMaster.AspNetCore.LetsEncrypt 0.5.0, as we didn't see that issue with that build.
I'm wondering if it might be exposing a similar SChannel bug to #101?
I think there may be other occurrences where this occurs, as I believe I've seen the same exception when LettuceEncrypt needs to issue a new certificate, but I need to do some work to narrow that down.

**Comment by 0xStuart** [comment]
I have just run into this issue.  I built a reverse proxy server using LettuceEncrypt with YARP.

Some clients may access the API I am proxying by the IP number, and not the full domain name.  NGINX works. Using a browser you can ignore the warning, but Kestral/YARP/LettuceEncrypt doesn't even serve the request.  I get the error above.

**Comment by StiliyanHoody** [comment]
Same issue here.

**Comment by Tom-V** [comment]
As we noticed the same behavior, and needed a fix, I created a PR for this, as our use case is delivering a product to many customers on which we don't know if they want to use let's encrypt or own certificates, yet we want to support it.
So for now we are using the forked version in our test-environment :)
