### ISSUE TITLE
Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger'

### ISSUE THREAD

**Issue by duckula99** [natemcmaster/LettuceEncrypt#125]
Using samples I could not get things working and was getting the error above.
I am using .Net Core 3.1, LettuceEncrypt 1.10-beta.60

I am not sure if this is right but it removed my error;-  I made the following changes to Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            //-->HERE
            var serviceProvider = services.BuildServiceProvider();
            var logger = serviceProvider.GetService<ILogger<Program>>();
            services.AddSingleton(typeof(ILogger), logger);
            //END HERE

            services.AddLettuceEncrypt();
       }

Hope this helps others

**Comment by Tratcher** [comment]
Never call BuildServiceProvider, it creates duplicate singletons.

What was the callstack for your original exception?

**Comment by duckula99** [comment]
Thanks for taking the time to read.  Below is the exception.

fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      ACME state machine encountered unhandled error
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'LettuceEncrypt.Internal.AcmeCertificateFactory'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at LettuceEncrypt.Internal.AcmeStates.AcmeState.MoveTo[T]()
   at LettuceEncrypt.Internal.AcmeStates.ServerStartupState.MoveNext()
   at LettuceEncrypt.Internal.AcmeStates.SyncAcmeState.MoveNextAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateLoader.ExecuteAsync(CancellationToken stoppingToken)
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://localhost:5000
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: https://localhost:5001
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: C:\Users\j?????\source\repos\LettuceEncypt\bin\Debug\netcoreapp3.1

**Comment by Tratcher** [comment]
Why does AcmeCertificateFactory take an `ILogger`? It should take an `ILogger<AcmeCertificateFactory>` or an `ILoggerFactory`.

**Comment by duckula99** [comment]
I truly do not know.  Perhaps it would help for me to explain my process.
1.  Open .Net Core Template from Visual Studio Community ver 16.6.2
2.  Use Manage Nuget Packet to install LettuceEncrypt ver1.1.0-beta.60
3.  Copy the contents of LettuceEncrypt/samples/Web/Program.cs & Startup.cs to my project
4. Edit appsettings.json to my settings

That all I am really doing.  Am I missing a step?

**Comment by duckula99** [comment]
OK, I got it.  My bad.  I am kicking myself.
My steps above seem to be fine.
Note for Others, Don't name your project "LettuceEncrypt".

**Comment by natemcmaster** [comment]
> It should take an ILogger<AcmeCertificateFactory> or an ILoggerFactory.

If you know how to fix it, pull requests are welcome :)

**Comment by duckula99** [comment]
I don't know how to fix it.  I am still trying things but I clearly do not know enough.

I changed this 
services.AddLettuceEncrypt().PersistDataToDirectory(new DirectoryInfo("./LettuceEncrypt/"), "qwert123");
to this
services.AddLettuceEncrypt(); <-- as what is in the sample.

The error changed to 
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      ACME state machine encountered unhandled error
System.InvalidOperationException: Unable to resolve service for type 'LettuceEncrypt.Accounts.IAccountStore' while attempting to activate 'LettuceEncrypt.Internal.AcmeCertificateFactory'.

I implemented
            services.AddLettuceEncrypt();
            services.AddSingleton<IAccountStore, MyAccountStore>();

and that took me back to
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      ACME state machine encountered unhandled error
System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Extensions.Logging.ILogger' while attempting to activate 'LettuceEncrypt.Internal.AcmeCertificateFactory'.

I know its something I am missing

**Comment by carey-bishop** [comment]
@duckula99 What do you have in your Program.cs?

There should be a call to ```Host.CreateDefaultBuilder(args)```. It's responsible for setting up the logging infrastructure and other core services.

**Comment by natemcmaster** [comment]
@duckula99, sorry my last comment was directed at @Tratcher.

Does it work if you also call `services.AddLogging();`?

**Comment by duckula99** [comment]
Thanks everyone for there information.
It seems I am successful.  

I am going to show my steps for others.  Please send comments for others as my steps are likely wrong.
My Steps are related to butchering the web sample and getting results

1.  Open .Net Core Template from Visual Studio Community (I used ver 16.6.2)
2.  Use Manage Nuget Packet to install LettuceEncrypt ver1.1.0-beta.60
3.  Copy the contents of LettuceEncrypt/samples/Web/Program.cs & Startup.cs to my project
4.  replace this in Startup.cs            
services.AddLettuceEncrypt();
with
        //-->HERE
        var serviceProvider = services.BuildServiceProvider();
        var logger = serviceProvider.GetService<ILogger<Program>>();
        services.AddSingleton(typeof(ILogger), logger);

services.AddLettuceEncrypt().PersistDataToDirectory(new DirectoryInfo("c:/LettuceEncrypt/"), "passwordhere");
        //END HERE
Adding the PersistDataToDirectory avoids the IAccountStore error (and having to add the code to deal with it) also it saves the certs to file which was satisfying
Adding the ILogger stuff got rid of the original error that I had (not recommended by others)
5.  Edit appsettings.json to my settings
6.  Set the environment variable on the device at the command line
set CONFIG_KESTREL_VIA_CODE=true
--------------------
The results
info: LettuceEncrypt.Internal.AcmeStates.ServerStartupState[0]
      Created certificate CN=*****.****.com (F0BCE884A204550??????????????????????????)
trce: LettuceEncrypt.Internal.CertificateSelector[0]
      Successfully tested certificate chain for ****.****.com
trce: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      ACME state transition: moving to CheckForRenewalState
-------------------


I was getting these errors on my Windows 10 machine as well as my Windows IOT (RPi).
Its officially running on my Pi now and I have "Hello World!".

@natemcmaster  Thanks so much for starting this project you have made a smile in the world.
If I can help with anything let me know.  For now I am celebrating a small victory.

**Comment by duckula99** [comment]
Last update.
I am no longer needing to add  (I was told it was bad but it did help me a lot)
`var serviceProvider = services.BuildServiceProvider(); var logger = serviceProvider.GetService<ILogger<Program>>(); services.AddSingleton(typeof(ILogger), logger);`

I believe the true cause of my issue was
`services.AddLettuceEncrypt().PersistDataToDirectory(new DirectoryInfo("./LettuceEncrypt/"), "passwordhere");` 

This command requires an absolute path from what I can tell.  Eg.
`services.AddLettuceEncrypt().PersistDataToDirectory(new DirectoryInfo("c:/LettuceEncrypt/"), "passwordhere");`

Hopefully my journey is complete and this helps others.
Thanks to all.

**Comment by natemcmaster** [comment]
Should be fixed in the latest 1.1.0 beta on NuGet.org.
