### ISSUE TITLE
Failed to validate ownership of domain

### ISSUE THREAD

**Issue by VoIPTools** [natemcmaster/LettuceEncrypt#158]
I created a generic ASP.Net API project and I'm following the developer instructions and using ngrok.  I keep getting the following error:
 
fail: LettuceEncrypt.Internal.AcmeCertificateLoader[0]
      Failed to validate ownership of domainName '0884dd10f800.ngrok.io'. Reason: urn:ietf:params:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge, Code = Forbidden

I see in ngrok:

GET /.well-known/acme-challenge/PPLGfHvD3OOOPrTjH1f4OrsF-bxgw49HruQYUH7Bses 200 OK

Why?

**Comment by VoIPTools** [comment]
If I set:

 UseStagingServer = true;

Then everything seems to work, except that I don't get a real certificate.

**Comment by BrnPer** [comment]
I'm also facing this issue 😔 Can somebody help? I have my API running at port 80...

**Comment by edwinhuish** [comment]
same issue here

**Comment by natemcmaster** [comment]
Sorry for long delays on responses. I am merging a refactor of domain validation. It has been really hard to test and reproduce these kinds of errors, but I think I found an important thing this library was doing wrong. The fix should be in the 1.1.0 version of this library, which I intended to release soon. Please give the updated and open an new issue if you still have errors.

**Comment by huangmingji** [comment]
I use YARP for load balancing in.net8 and LettuceEncrypt1.3.3 have the same problem. How can I solve it?
`
[16:13:32 ERR] Failed to validate ownership of domainName 'git.stargazer.tech'. Reason: urn:ietf:params:acme:error:unauthorized: Cannot negotiate ALPN protocol "acme-tls/1" for tls-alpn-01 challenge, Code = Forbidden
[16:13:32 DBG] Validation with TlsAlpn01DomainValidator failed with error: Failed to validate ownership of domainName 'git.stargazer.tech'
System.InvalidOperationException: Failed to validate ownership of domainName 'git.stargazer.tech'
   at LettuceEncrypt.Internal.DomainOwnershipValidator.WaitForChallengeResultAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.TlsAlpn01DomainValidator.ValidateOwnershipAsync(IAuthorizationContext authzContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
[16:13:32 DBG] Validation with Http01DomainValidator failed with error: Did not receive challenge information for challenge type http-01
System.InvalidOperationException: Did not receive challenge information for challenge type http-01
   at LettuceEncrypt.Internal.Http01DomainValidator.PrepareHttpChallengeResponseAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.Http01DomainValidator.ValidateOwnershipAsync(IAuthorizationContext authzContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
[16:13:33 DBG] Validation with Dns01DomainValidator failed with error: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at LettuceEncrypt.Internal.Dns01DomainValidator.PrepareDns01ChallengeResponseAsync(IAuthorizationContext authorizationContext, String domainName, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.Dns01DomainValidator.ValidateOwnershipAsync(IAuthorizationContext authzContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.Dns01DomainValidator.ValidateOwnershipAsync(IAuthorizationContext authzContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
[16:13:33 ERR] Failed to automatically create a certificate for git.stargazer.tech
System.InvalidOperationException: Failed to validate ownership of domainName 'git.stargazer.tech'
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
[16:13:33 ERR] ACME state machine encountered unhandled error
System.InvalidOperationException: Failed to validate ownership of domainName 'git.stargazer.tech'
   at LettuceEncrypt.Internal.AcmeCertificateFactory.ValidateDomainOwnershipAsync(IAuthorizationContext authorizationContext, CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
   at LettuceEncrypt.Internal.AcmeCertificateLoader.ExecuteAsync(CancellationToken stoppingToken)
`
