### ISSUE TITLE
NullReferenceException @ LettuceEncrypt.Internal.AcmeClient.GetOrderAuthorizations(IOrderContext orderContext)

### ISSUE THREAD

**Issue by petrechitashvili** [natemcmaster/LettuceEncrypt#232]
Here's the exception from my dockerized blazor server app:

```
blazor        | [08:03:50 INF] Creating new account for [email.address]
blazor        | [08:03:52 INF] Using account 294704460
blazor        | [08:03:52 INF] Creating certificate for [domain]
blazor        | [08:03:58 ERR] Failed to automatically create a certificate for [domain]
blazor        | System.NullReferenceException: Object reference not set to an instance of an object.
blazor        |    at Certes.Acme.OrderContext.Authorizations()
blazor        |    at LettuceEncrypt.Internal.AcmeClient.GetOrderAuthorizations(IOrderContext orderContext)
blazor        |    at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
blazor        |    at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
blazor        | [08:03:58 ERR] ACME state machine encountered unhandled error
blazor        | System.NullReferenceException: Object reference not set to an instance of an object.
blazor        |    at Certes.Acme.OrderContext.Authorizations()
blazor        |    at LettuceEncrypt.Internal.AcmeClient.GetOrderAuthorizations(IOrderContext orderContext)
blazor        |    at LettuceEncrypt.Internal.AcmeCertificateFactory.CreateCertificateAsync(CancellationToken cancellationToken)
blazor        |    at LettuceEncrypt.Internal.AcmeStates.BeginCertificateCreationState.MoveNextAsync(CancellationToken cancellationToken)
blazor        |    at LettuceEncrypt.Internal.AcmeCertificateLoader.ExecuteAsync(CancellationToken stoppingToken)
```

These are the configuration options:

`appsettings.json`
```json
"LettuceEncrypt": {
    "AcceptTermsOfService": true,
    "DomainNames": [ "[domain]" ],
    "EmailAddress": "[email.address]"
  }
```

`Startup.cs`
```csharp
services.AddLettuceEncrypt();
```

**Comment by natemcmaster** [comment]
I'm unable to reproduce the problem with the information provided. Please provide more steps to recreate this problem.
